// Code generated by protoc-gen-go. DO NOT EDIT.
// source: leveldb.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TxInput struct {
	TxId                 uint32   `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	PkId                 uint32   `protobuf:"varint,2,opt,name=pk_id,json=pkId,proto3" json:"pk_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInput) Reset()         { *m = TxInput{} }
func (m *TxInput) String() string { return proto.CompactTextString(m) }
func (*TxInput) ProtoMessage()    {}
func (*TxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{0}
}

func (m *TxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInput.Unmarshal(m, b)
}
func (m *TxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInput.Marshal(b, m, deterministic)
}
func (m *TxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInput.Merge(m, src)
}
func (m *TxInput) XXX_Size() int {
	return xxx_messageInfo_TxInput.Size(m)
}
func (m *TxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInput.DiscardUnknown(m)
}

var xxx_messageInfo_TxInput proto.InternalMessageInfo

func (m *TxInput) GetTxId() uint32 {
	if m != nil {
		return m.TxId
	}
	return 0
}

func (m *TxInput) GetPkId() uint32 {
	if m != nil {
		return m.PkId
	}
	return 0
}

type TxOutput struct {
	PkId                 uint32   `protobuf:"varint,1,opt,name=pk_id,json=pkId,proto3" json:"pk_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutput) Reset()         { *m = TxOutput{} }
func (m *TxOutput) String() string { return proto.CompactTextString(m) }
func (*TxOutput) ProtoMessage()    {}
func (*TxOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{1}
}

func (m *TxOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutput.Unmarshal(m, b)
}
func (m *TxOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutput.Marshal(b, m, deterministic)
}
func (m *TxOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutput.Merge(m, src)
}
func (m *TxOutput) XXX_Size() int {
	return xxx_messageInfo_TxOutput.Size(m)
}
func (m *TxOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutput proto.InternalMessageInfo

func (m *TxOutput) GetPkId() uint32 {
	if m != nil {
		return m.PkId
	}
	return 0
}

type TxMsg struct {
	TxHash               []byte      `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockHeight          uint32      `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Inputs               []*TxInput  `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*TxOutput `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TxMsg) Reset()         { *m = TxMsg{} }
func (m *TxMsg) String() string { return proto.CompactTextString(m) }
func (*TxMsg) ProtoMessage()    {}
func (*TxMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{2}
}

func (m *TxMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxMsg.Unmarshal(m, b)
}
func (m *TxMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxMsg.Marshal(b, m, deterministic)
}
func (m *TxMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxMsg.Merge(m, src)
}
func (m *TxMsg) XXX_Size() int {
	return xxx_messageInfo_TxMsg.Size(m)
}
func (m *TxMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TxMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TxMsg proto.InternalMessageInfo

func (m *TxMsg) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *TxMsg) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *TxMsg) GetInputs() []*TxInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TxMsg) GetOutputs() []*TxOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type PkMsg struct {
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	UId  uint32 `protobuf:"varint,2,opt,name=u_id,json=uId,proto3" json:"u_id,omitempty"`
	// TODO: Add type
	TxId                 []uint32 `protobuf:"varint,3,rep,packed,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PkMsg) Reset()         { *m = PkMsg{} }
func (m *PkMsg) String() string { return proto.CompactTextString(m) }
func (*PkMsg) ProtoMessage()    {}
func (*PkMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{3}
}

func (m *PkMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkMsg.Unmarshal(m, b)
}
func (m *PkMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkMsg.Marshal(b, m, deterministic)
}
func (m *PkMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkMsg.Merge(m, src)
}
func (m *PkMsg) XXX_Size() int {
	return xxx_messageInfo_PkMsg.Size(m)
}
func (m *PkMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PkMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PkMsg proto.InternalMessageInfo

func (m *PkMsg) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *PkMsg) GetUId() uint32 {
	if m != nil {
		return m.UId
	}
	return 0
}

func (m *PkMsg) GetTxId() []uint32 {
	if m != nil {
		return m.TxId
	}
	return nil
}

type UserMsg struct {
	TxId                 []uint32 `protobuf:"varint,1,rep,packed,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	PkId                 []uint32 `protobuf:"varint,2,rep,packed,name=pk_id,json=pkId,proto3" json:"pk_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMsg) Reset()         { *m = UserMsg{} }
func (m *UserMsg) String() string { return proto.CompactTextString(m) }
func (*UserMsg) ProtoMessage()    {}
func (*UserMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{4}
}

func (m *UserMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMsg.Unmarshal(m, b)
}
func (m *UserMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMsg.Marshal(b, m, deterministic)
}
func (m *UserMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMsg.Merge(m, src)
}
func (m *UserMsg) XXX_Size() int {
	return xxx_messageInfo_UserMsg.Size(m)
}
func (m *UserMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UserMsg proto.InternalMessageInfo

func (m *UserMsg) GetTxId() []uint32 {
	if m != nil {
		return m.TxId
	}
	return nil
}

func (m *UserMsg) GetPkId() []uint32 {
	if m != nil {
		return m.PkId
	}
	return nil
}

func init() {
	proto.RegisterType((*TxInput)(nil), "protos.TxInput")
	proto.RegisterType((*TxOutput)(nil), "protos.TxOutput")
	proto.RegisterType((*TxMsg)(nil), "protos.TxMsg")
	proto.RegisterType((*PkMsg)(nil), "protos.PkMsg")
	proto.RegisterType((*UserMsg)(nil), "protos.UserMsg")
}

func init() { proto.RegisterFile("leveldb.proto", fileDescriptor_f05cac86d12486b9) }

var fileDescriptor_f05cac86d12486b9 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x15, 0x9c, 0x3f, 0x70, 0x6d, 0x05, 0x98, 0x81, 0x6c, 0x94, 0x2c, 0x54, 0x0c, 0x1d,
	0xe8, 0x23, 0xb0, 0x34, 0x03, 0x02, 0x59, 0x61, 0x8e, 0x12, 0x1c, 0xd5, 0x51, 0x22, 0x12, 0xc5,
	0x17, 0xe4, 0x47, 0xe1, 0x71, 0x91, 0xcf, 0xae, 0xda, 0x81, 0xc9, 0xd6, 0xe7, 0xcf, 0xa7, 0xdf,
	0xfd, 0x60, 0xd5, 0x37, 0x3f, 0x4d, 0x2f, 0xeb, 0xed, 0x38, 0x0d, 0x38, 0xf0, 0x98, 0x0e, 0x9d,
	0xed, 0x20, 0x29, 0x4c, 0xfe, 0x3d, 0xce, 0xc8, 0xef, 0x20, 0x42, 0x53, 0xb6, 0x32, 0x0d, 0xd6,
	0xc1, 0x66, 0x25, 0x42, 0x34, 0xb9, 0xb4, 0xe1, 0xd8, 0xd9, 0xf0, 0xc2, 0x85, 0x63, 0x97, 0xcb,
	0xec, 0x01, 0x2e, 0x0b, 0xf3, 0x3e, 0xa3, 0xff, 0xe5, 0x0a, 0xc1, 0x59, 0xe1, 0x37, 0x80, 0xa8,
	0x30, 0x6f, 0xfa, 0xc0, 0xef, 0x21, 0x41, 0x53, 0xaa, 0x4a, 0x2b, 0x2a, 0x2c, 0x45, 0x8c, 0x66,
	0x5f, 0x69, 0xc5, 0x1f, 0x61, 0x59, 0xf7, 0xc3, 0x57, 0x57, 0xaa, 0xa6, 0x3d, 0x28, 0xf4, 0xf3,
	0x17, 0x94, 0xed, 0x29, 0xe2, 0x4f, 0x10, 0xb7, 0x96, 0x4c, 0xa7, 0x6c, 0xcd, 0x36, 0x8b, 0x97,
	0x6b, 0xc7, 0xae, 0xb7, 0x9e, 0x58, 0xf8, 0x67, 0xfe, 0x0c, 0xc9, 0x40, 0x34, 0x3a, 0x0d, 0xa9,
	0x79, 0x73, 0x6a, 0x3a, 0x4c, 0x71, 0x2c, 0x64, 0xaf, 0x10, 0x7d, 0x74, 0x96, 0x8c, 0x43, 0x58,
	0x49, 0x39, 0x11, 0xd6, 0x95, 0xa0, 0x3b, 0xbf, 0x85, 0x70, 0x3e, 0x2d, 0xcb, 0x66, 0x27, 0xc0,
	0x59, 0xb1, 0x0c, 0xde, 0x8a, 0xb5, 0xf6, 0xa9, 0x9b, 0xc9, 0x8e, 0x39, 0xb3, 0xc6, 0xfe, 0xb3,
	0xc6, 0x8e, 0x52, 0x6a, 0xa7, 0x7c, 0xf7, 0x17, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x6c, 0x8e, 0x5d,
	0x8a, 0x01, 0x00, 0x00,
}
