// Code generated by protoc-gen-go. DO NOT EDIT.
// source: leveldb.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UtxoMsg struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Pid                  uint32   `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	TidCreate            uint32   `protobuf:"varint,4,opt,name=tid_create,json=tidCreate,proto3" json:"tid_create,omitempty"`
	TidSpend             uint32   `protobuf:"varint,5,opt,name=tid_spend,json=tidSpend,proto3" json:"tid_spend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UtxoMsg) Reset()         { *m = UtxoMsg{} }
func (m *UtxoMsg) String() string { return proto.CompactTextString(m) }
func (*UtxoMsg) ProtoMessage()    {}
func (*UtxoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{0}
}

func (m *UtxoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UtxoMsg.Unmarshal(m, b)
}
func (m *UtxoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UtxoMsg.Marshal(b, m, deterministic)
}
func (m *UtxoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UtxoMsg.Merge(m, src)
}
func (m *UtxoMsg) XXX_Size() int {
	return xxx_messageInfo_UtxoMsg.Size(m)
}
func (m *UtxoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UtxoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UtxoMsg proto.InternalMessageInfo

func (m *UtxoMsg) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *UtxoMsg) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UtxoMsg) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *UtxoMsg) GetTidCreate() uint32 {
	if m != nil {
		return m.TidCreate
	}
	return 0
}

func (m *UtxoMsg) GetTidSpend() uint32 {
	if m != nil {
		return m.TidSpend
	}
	return 0
}

type TxMsg struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Inputs               []uint64 `protobuf:"varint,3,rep,packed,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []uint64 `protobuf:"varint,4,rep,packed,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxMsg) Reset()         { *m = TxMsg{} }
func (m *TxMsg) String() string { return proto.CompactTextString(m) }
func (*TxMsg) ProtoMessage()    {}
func (*TxMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{1}
}

func (m *TxMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxMsg.Unmarshal(m, b)
}
func (m *TxMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxMsg.Marshal(b, m, deterministic)
}
func (m *TxMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxMsg.Merge(m, src)
}
func (m *TxMsg) XXX_Size() int {
	return xxx_messageInfo_TxMsg.Size(m)
}
func (m *TxMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TxMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TxMsg proto.InternalMessageInfo

func (m *TxMsg) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *TxMsg) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TxMsg) GetInputs() []uint64 {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TxMsg) GetOutputs() []uint64 {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type PkMsg struct {
	Pkey                 []byte   `protobuf:"bytes,1,opt,name=pkey,proto3" json:"pkey,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Wid                  uint32   `protobuf:"varint,3,opt,name=wid,proto3" json:"wid,omitempty"`
	Tid                  []uint32 `protobuf:"varint,4,rep,packed,name=tid,proto3" json:"tid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PkMsg) Reset()         { *m = PkMsg{} }
func (m *PkMsg) String() string { return proto.CompactTextString(m) }
func (*PkMsg) ProtoMessage()    {}
func (*PkMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{2}
}

func (m *PkMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkMsg.Unmarshal(m, b)
}
func (m *PkMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkMsg.Marshal(b, m, deterministic)
}
func (m *PkMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkMsg.Merge(m, src)
}
func (m *PkMsg) XXX_Size() int {
	return xxx_messageInfo_PkMsg.Size(m)
}
func (m *PkMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PkMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PkMsg proto.InternalMessageInfo

func (m *PkMsg) GetPkey() []byte {
	if m != nil {
		return m.Pkey
	}
	return nil
}

func (m *PkMsg) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PkMsg) GetWid() uint32 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *PkMsg) GetTid() []uint32 {
	if m != nil {
		return m.Tid
	}
	return nil
}

type WalletMsg struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Pid                  []uint32 `protobuf:"varint,3,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletMsg) Reset()         { *m = WalletMsg{} }
func (m *WalletMsg) String() string { return proto.CompactTextString(m) }
func (*WalletMsg) ProtoMessage()    {}
func (*WalletMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{3}
}

func (m *WalletMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletMsg.Unmarshal(m, b)
}
func (m *WalletMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletMsg.Marshal(b, m, deterministic)
}
func (m *WalletMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletMsg.Merge(m, src)
}
func (m *WalletMsg) XXX_Size() int {
	return xxx_messageInfo_WalletMsg.Size(m)
}
func (m *WalletMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletMsg.DiscardUnknown(m)
}

var xxx_messageInfo_WalletMsg proto.InternalMessageInfo

func (m *WalletMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WalletMsg) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *WalletMsg) GetPid() []uint32 {
	if m != nil {
		return m.Pid
	}
	return nil
}

type BlockMsg struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Ntx                  uint32   `protobuf:"varint,3,opt,name=ntx,proto3" json:"ntx,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	HashPrev             []byte   `protobuf:"bytes,5,opt,name=hash_prev,json=hashPrev,proto3" json:"hash_prev,omitempty"`
	Ts                   uint32   `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`
	Bits                 uint32   `protobuf:"varint,7,opt,name=bits,proto3" json:"bits,omitempty"`
	Nonce                uint32   `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Size                 uint32   `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMsg) Reset()         { *m = BlockMsg{} }
func (m *BlockMsg) String() string { return proto.CompactTextString(m) }
func (*BlockMsg) ProtoMessage()    {}
func (*BlockMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05cac86d12486b9, []int{4}
}

func (m *BlockMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMsg.Unmarshal(m, b)
}
func (m *BlockMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMsg.Marshal(b, m, deterministic)
}
func (m *BlockMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMsg.Merge(m, src)
}
func (m *BlockMsg) XXX_Size() int {
	return xxx_messageInfo_BlockMsg.Size(m)
}
func (m *BlockMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMsg proto.InternalMessageInfo

func (m *BlockMsg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockMsg) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BlockMsg) GetNtx() uint32 {
	if m != nil {
		return m.Ntx
	}
	return 0
}

func (m *BlockMsg) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockMsg) GetHashPrev() []byte {
	if m != nil {
		return m.HashPrev
	}
	return nil
}

func (m *BlockMsg) GetTs() uint32 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *BlockMsg) GetBits() uint32 {
	if m != nil {
		return m.Bits
	}
	return 0
}

func (m *BlockMsg) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockMsg) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*UtxoMsg)(nil), "protos.UtxoMsg")
	proto.RegisterType((*TxMsg)(nil), "protos.TxMsg")
	proto.RegisterType((*PkMsg)(nil), "protos.PkMsg")
	proto.RegisterType((*WalletMsg)(nil), "protos.WalletMsg")
	proto.RegisterType((*BlockMsg)(nil), "protos.BlockMsg")
}

func init() { proto.RegisterFile("leveldb.proto", fileDescriptor_f05cac86d12486b9) }

var fileDescriptor_f05cac86d12486b9 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x8a, 0xd4, 0x40,
	0x10, 0x65, 0x26, 0xc9, 0x24, 0x29, 0x36, 0x22, 0x8d, 0x48, 0xc3, 0x22, 0x0c, 0x39, 0xcd, 0xc9,
	0x8b, 0x7f, 0xa0, 0x78, 0x14, 0x96, 0x5e, 0xc5, 0xe3, 0x90, 0x99, 0x2e, 0x36, 0xcd, 0xc6, 0x4e,
	0x48, 0x57, 0xb2, 0x59, 0x2f, 0x7e, 0xa1, 0xff, 0x24, 0x55, 0x9d, 0xa8, 0x97, 0x3d, 0xe5, 0xbd,
	0x57, 0xcd, 0x7b, 0x5d, 0x2f, 0x0d, 0x55, 0x87, 0x33, 0x76, 0xf6, 0xf2, 0x7e, 0x18, 0x7b, 0xea,
	0xd5, 0x41, 0x3e, 0xa1, 0xfe, 0x05, 0xf9, 0x37, 0x5a, 0xfa, 0x2f, 0xe1, 0x41, 0xbd, 0x81, 0x6c,
	0x6e, 0xba, 0x09, 0xf5, 0xee, 0xb8, 0x3b, 0xa5, 0x26, 0x12, 0xf5, 0x1a, 0x92, 0xc9, 0x59, 0xbd,
	0x17, 0x8d, 0x21, 0x2b, 0x83, 0xb3, 0x3a, 0x39, 0xee, 0x4e, 0x95, 0x61, 0xa8, 0xde, 0x01, 0x90,
	0xb3, 0xe7, 0xeb, 0x88, 0x0d, 0xa1, 0x4e, 0x65, 0x50, 0x92, 0xb3, 0x9f, 0x44, 0x50, 0xb7, 0xc0,
	0xe4, 0x1c, 0x06, 0xf4, 0x56, 0x67, 0x32, 0x2d, 0xc8, 0xd9, 0x7b, 0xe6, 0x35, 0x42, 0xf6, 0x75,
	0xe1, 0x78, 0x05, 0x69, 0xdb, 0x84, 0x56, 0xd2, 0x6f, 0x8c, 0x60, 0xf5, 0x16, 0x0e, 0x2d, 0xba,
	0x87, 0x96, 0x24, 0xbf, 0x32, 0x2b, 0x63, 0xdd, 0xf9, 0x61, 0xa2, 0xa0, 0x93, 0x63, 0x72, 0x4a,
	0xcd, 0xca, 0x94, 0x86, 0xbc, 0x9f, 0x48, 0x06, 0xa9, 0x0c, 0x36, 0x5a, 0xdf, 0x43, 0x76, 0xf7,
	0xb8, 0xc6, 0x0c, 0x8f, 0xf8, 0xbc, 0xc5, 0x30, 0x66, 0x8d, 0x9e, 0x07, 0x5c, 0x43, 0x04, 0xf3,
	0x96, 0x4f, 0xff, 0xb6, 0x7c, 0x8a, 0x7b, 0x93, 0xb3, 0x62, 0x5c, 0x19, 0x86, 0xf5, 0x67, 0x28,
	0xbf, 0x37, 0x5d, 0x87, 0xb4, 0x1a, 0xfb, 0xe6, 0x47, 0x6c, 0xaf, 0x34, 0x82, 0x5f, 0x32, 0x8e,
	0xf5, 0x25, 0x6b, 0x7d, 0xf5, 0xef, 0x1d, 0x14, 0x1f, 0xbb, 0xfe, 0x2a, 0xf7, 0xd3, 0x90, 0xcf,
	0x38, 0x06, 0xd7, 0x7b, 0x71, 0xaa, 0xcc, 0x46, 0x79, 0xe9, 0x40, 0x0d, 0x4d, 0x61, 0x2b, 0x23,
	0x32, 0x36, 0xf4, 0xb4, 0x6c, 0x37, 0xf5, 0xb4, 0xfc, 0xad, 0x32, 0xfd, 0xaf, 0xca, 0x5b, 0x28,
	0xf9, 0x7b, 0x1e, 0x46, 0x9c, 0xe5, 0x27, 0xdc, 0x98, 0x82, 0x85, 0xbb, 0x11, 0x67, 0xf5, 0x0a,
	0xf6, 0x14, 0xf4, 0x41, 0x1c, 0xf6, 0x14, 0xd8, 0xe0, 0xe2, 0x28, 0xe8, 0x3c, 0xde, 0x9b, 0x31,
	0x3f, 0x0f, 0xdf, 0xfb, 0x2b, 0xea, 0x42, 0xc4, 0x48, 0xf8, 0x64, 0x70, 0x3f, 0x51, 0x97, 0xf1,
	0x24, 0xe3, 0x4b, 0x7c, 0x5b, 0x1f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xde, 0x55, 0xa0, 0x82,
	0x73, 0x02, 0x00, 0x00,
}
